# site title
title: Read list

# user name or organization name
user: yasongxu

# issue repository
repository: ReadList

# multi-author
authors: yasongxu

# token
# token should be separated by '#'
# example: 5#c31bffc137f44faf7efc4a84da827g7ca2cfeaa
token: d#98a001bdcf17f39b3200857d26f0ae07b04c234

# posts per page
perpage: 15


# advance config

# organization repository (?)
organization: false

# post order
# order by create time" or "update time"
# 'UPDATED_AT' or 'CREATED_AT'
order: 'UPDATED_AT'
