apiVersion: "cluster.k8s.io/v1alpha1"
kind: Cluster
metadata:
  name: cluster-sample
spec:
    clusterNetwork:
        services:
            cidrBlocks: ["10.96.0.0/16"]
        pods:
            cidrBlocks: ["100.10.0.0/16"]
        serviceDomain: "cluster.local"
    providerSpec:
      value:
        apiVersion: "cceproviderconfig/v1alpha1"
        kind: "CCEClusterProviderConfig"
        clusterName: "cluster-test3"
        clusterCIDR: "172.30.0.0/19"
        
        
apiVersion: "cluster.k8s.io/v1alpha1"
kind: MachineDeployment
metadata:
  name: sample-master
spec:
  replicas: 1
  selector:
    matchLabels:
      foo: bar
  template:
    metadata:
      labels:
        foo: bar
    spec:
      providerSpec:
        value:
          apiVersion: "cceproviderconfig/v1alpha1"
          kind: "CCEMachineProviderConfig"
          clusterName: "cluster-test3"
          role: "master"
          adminPass: "testpw123!"
          imageId: "m-8WV4kRlN" # ubuntu 16.04 lts amd64
          cpuCount: 2
          memoryCapacityInGB: 2
      versions:
        kubelet: 1.12.3
        controlPlane: 1.12.3
  strategy:
    type: "RollingUpdate"
    rollingUpdate:
      maxUnavailable: "30%"
      maxSurge: "30%"
  minReadySeconds: 2
---

apiVersion: cce.baidubce.com/v1
kind: Cluster
metadata:
  name: cce-5t277sd0
  namespace: default
spec:
  accountID: eca97e148cb74e9683d7b7240829d1ff
  clusterID: cce-5t277sd0
  clusterName: sun-ipv6
  clusterType: normal
  containerNetworkConfig:
    clusterIPServiceCIDR: 192.168.96.0/19
    clusterIPServiceCIDRIPv6: fdff:ffff:ffff:ffff:ffff:ffff:ffff:c000/115
    clusterPodCIDR: 172.16.0.0/17
    clusterPodCIDRIPv6: fc01::/17
    ipVersion: dualStack
    kubeProxyMode: ipvs
    lbServiceVPCSubnetID: sbn-jxfd3ayb00n6
    maxPodsPerNode: 128
    mode: kubenet
    nodePortRangeMax: 32767
    nodePortRangeMin: 30000
  handler: default
  k8sCustomConfig:
    kubeAPIQPS: 10
  k8sVersion: 1.16.3
  masterConfig:
    clusterBLBVPCSubnetID: sbn-jxfd3ayb00n6
    clusterHA: 1
    customBCCClusterMasterOption: {}
    managedClusterMasterOption: {}
    masterType: existed_bcc
  plugins:
  - core-dns
  - cni
  runtimeType: docker
  runtimeVersion: 18.09.07
  userID: eca97e148cb74e9683d7b7240829d1ff
  vpcCIDR: 10.0.0.0/16
  vpcCIDRIPv6: 240c:4085:0:3600::/56
  vpcID: vpc-hhkb5gfz71gr
  vpcUUID: 55883ef0-34a4-4243-bdca-db2954b20013
status:
  apiServerAccessSuccess: true
  apiServerWhiteList:
  - 100.64.0.179
  - 10.0.0.13
  - 10.0.0.6
  - 100.72.113.98
  - 192.168.96.1
  clusterBLB:
    description: Generated by CCE cce-5t277sd0, Do not edit manually
    floatingIP: 100.64.0.179
    id: lb-56d91459
    name: CCE/ClusterBLB/cce-5t277sd0
    uuid: 6f6b727838325146465846717061314a4f39384332513d3d
    vpcIP: 10.0.0.13
  clusterPhase: running
  externalETCD: {}
  infrastructureReady: true
  k8sPluginDeploySuccess: true
  reconcileSteps:
    CreateCertificateAuthority:
      costSeconds: 1
      finishedTime: "2020-06-29T06:02:31Z"
      ready: true
      retryCount: 1
      startTime: "2020-06-29T06:02:30Z"
    CreateClusterInfrastructure:
      costSeconds: 53
      finishedTime: "2020-06-29T06:03:24Z"
      ready: true
      retryCount: 1
      startTime: "2020-06-29T06:02:31Z"
    CreateClusterLB:
      costSeconds: 16
      finishedTime: "2020-06-29T06:02:47Z"
      ready: true
      retryCount: 1
      startTime: "2020-06-29T06:02:31Z"
    DeployK8SPlugin:
      costSeconds: 20
      finishedTime: "2020-06-29T06:04:39Z"
      ready: true
      retryCount: 1
      startTime: "2020-06-29T06:04:19Z"
    WaitAPIServerAccess:
      costSeconds: 55
      finishedTime: "2020-06-29T06:04:19Z"
      ready: true
      retryCount: 3
      startTime: "2020-06-29T06:03:24Z"
    WaitMasterInfrastructure:
      costSeconds: 37
      finishedTime: "2020-06-29T06:03:24Z"
      ready: true
      retryCount: 1
      startTime: "2020-06-29T06:02:47Z"
